version: "2"
services:
 samba:
    image: dperson/samba
    container_name: smaba
    restart: always
    network_mode: bridge
    volumes:
      - /home/kris/lede:/share/lede
      - /home/kris/appdata:/share/appdata
    ports:
      - "445:445"
      - "139:139"
    command: -u "kris;password" -s "lede;/share/lede;yes;no;no;kris" -s "appdata;/share/appdata;yes;no;no;kris;kris"
